FROM rasa/rasa:2.6.0-full

USER root

# RUN mkdir -p /usr/src/app

WORKDIR /app

# COPY . /app
COPY data /app/data
# COPY models /app/models
COPY config.yml credentials.yml domain.yml endpoints.yml requirements.txt /app/

RUN pip install -r requirements.txt \
&& rasa train --domain domain.yml --data data --out models

EXPOSE 5005 5005

ENTRYPOINT ["rasa", "run", "-m", "models", "--endpoints", "endpoints.yml", "--cors", "*", "--deb"]
