FROM nginx:stable
COPY . /usr/share/nginx/html/
COPY frontend.conf /etc/nginx/conf.d/
RUN mv /etc/nginx/conf.d/default.conf /etc/nginx/conf.d/default.conf.disabled
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]